- platform: mqtt
  name: "Kitchen Light Switch Tap"
  state_topic: "cmnd/lswitch1-1/POWER"
  payload_on: "TOGGLE"
  qos: 1
  off_delay: "1"
- platform: mqtt
  name: "Kitchen Light Switch Hold"
  state_topic: "cmnd/lswitch1-1/POWER"
  payload_on: "HOLD"
  qos: 1
  off_delay: "1"
