- platform: template
  sensors:
    washing_machine:
      friendly_name: "Washing Machine"
      delay_off:
        minutes: 2
      value_template: >-
        {{ states('sensor.washer_current')|float > 0.1 }}
