- alias: 'Bedroom Ambient Light On'
  trigger:
    - platform: state
      entity_id: light.bedroom_lights
      to: 'off'
  action:
    - service: light.turn_on
      entity_id:
       - light.bedroom_underbesta_light

- alias: 'Bedroom Ambient Light Off'
  trigger:
    - platform: state
      entity_id: light.bedroom_lights
      to: 'on'
  action:
    - service: light.turn_off
      entity_id:
       - light.bedroom_underbesta_light
