- alias: Notify CallerID
  trigger: 
    platform: state
    entity_id: sensor.modem_callerid
    to: "callerid"
  action:
    service: notify.notify
    data:
      message: 'Call from {{ states.sensor.modem_callerid.attributes.cid_name }} at {{ states.sensor.modem_callerid.attributes.cid_number }} '
- alias: Notify CallerID webui
  trigger: 
    platform: state
    entity_id: sensor.modem_callerid
    to: "callerid"
  action:
    service: persistent_notification.create
    data:
      title: "Call from"
      message: '{{ states.sensor.modem_callerid.attributes.cid_time.strftime("%I:%M %p") }} {{ states.sensor.modem_callerid.attributes.cid_name }}  {{ states.sensor.modem_callerid.attributes.cid_number }} '
- alias: Say CallerID
  trigger: 
    platform: state
    entity_id: sensor.modem_callerid
    to: "callerid"
  action:
    - service: tts.google_say
      entity_id: media_player.upstate
      data_template:
        message: 'Call from {{ states.sensor.modem_callerid.attributes.cid_name }}'
    - service: tts.google_say
      entity_id: media_player.kitchen
      data_template:
        message: 'Call from {{ states.sensor.modem_callerid.attributes.cid_name }}'
    - service: media_player.alexa_tts
      entity_id: media_player.davids_bathroom
      data_template:
        message: 'Call from {{ states.sensor.modem_callerid.attributes.cid_name }}'


