- alias: 'Living Room Ambient Light On'
  trigger:
    - platform: state
      entity_id: light.living_room_lights
      to: 'off'
  action:
    - service: light.turn_on
      entity_id:
       - light.6001948c57cb_1011185 

- alias: 'Living Room Ambient Light Off'
  trigger:
    - platform: state
      entity_id: light.living_room_lights
      to: 'on'
  action:
    - service: light.turn_off
      entity_id:
       - light.6001948c57cb_1011185 

- alias: 'Living Room Lights Toggle'
  trigger:
    - platform: state
      entity_id: binary_sensor.living_room_outdoor_light_switch_tap
      to: 'on'
    - platform: state
      entity_id: binary_sensor.living_room_light_switch_tap
      to: 'on'
  action:
    - service: light.toggle
      entity_id:
       - light.living_room_high_hats
       - light.living_room_fan_light 
