- alias: rtl433_upstate_weather_convert49
  trigger:
    - platform: mqtt
      topic: sensors/rtl_433
  condition:
    condition: template
    value_template: >
      {% if trigger.payload_json.sensor_id %}
        {{ trigger.payload_json.sensor_id == 2695 and trigger.payload_json.message_type == 49 }}
      {% else %}
        false
      {% endif %}
  action:
    - service: mqtt.publish 
      data_template:
        topic: rtl433/upstate_weather49
        payload: '{ "wind_speed" : {{ trigger.payload_json.wind_speed }}, "wind_dir_deg" : {{ trigger.payload_json.wind_dir_deg }}, "wind_dir" : {{ trigger.payload_json.wind_dir }}, "rainfall_accumulation" : {{ trigger.payload_json.rainfall_accumulation }}, "rainfall_raw" : {{ trigger.payload_json.raincounter_raw }}, "model" : "{{ trigger.payload_json.model }}", "battery" : "{{ trigger.payload_json.battery }}"  }'
