light:
  - platform: mqtt
    name: "Bedroom Fan Light"
    state_topic: "stat/lswitch2/RESULT"
    value_template: '{{ value_json["POWER"] }}'
    command_topic: "cmnd/lswitch2/POWER"
    availability_topic: "tele/lswitch2/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false
sensor:
  - platform: mqtt
    name: "Bedroom Fan Light Switch State"
    state_topic: "cmnd/lswitch2-1/POWER"
    qos: 1
    expire_after: "1"
automation:
  - alias:  Bedroom Fan Light Double Tap
    trigger:
     - platform: state
       entity_id: sensor.bedroom_fan_light_switch_state
       to: 'TOGGLE'
    action:
      service: light.toggle
      data:
        entity_id: light.bedroom_mini_tracklight
  - alias: Bedroom Fan Light Hold
    trigger:
      - platform: state
        entity_id: sensor.bedroom_fan_light_switch_state
        to: 'HOLD'
    action:
      service: light.toggle
      data:
        entity_id: light.bedroom_tracklight
