light:
  - platform: mqtt
    name: "Outdoor Light"
    state_topic: "stat/lswitch4/RESULT"
    value_template: '{{ value_json["POWER"] }}'
    command_topic: "cmnd/lswitch4/POWER"
    availability_topic: "tele/lswitch4/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false
sensor:
  - platform: mqtt
    name: "Living Room Outdoor Light Switch State"
    state_topic: "cmnd/lswitch4-1/POWER"
    qos: 1
    expire_after: "1"
automation:
  - alias:  Outdoor Living Room Light Light Double Tap
    trigger:
     - platform: state
       entity_id: sensor.living_room_outdoor_light_switch_state
       to: 'TOGGLE'
    action:
      service: light.toggle
      data:
        entity_id: light.living_room_high_hats
  - alias: Outdoor Living Room Light Hold
    trigger:
      - platform: state
        entity_id: sensor.living_room_outdoor_light_switch_state
        to: 'HOLD'
    action:
      service: light.toggle
      data:
        entity_id: light.desk_lamp
