homeassistant:

# Ring Video Doorbell
ring:
  username: !secret ring_username
  password: !secret ring_password



sensor:
- platform: ring
  monitored_conditions:
    - battery
    - last_activity
    - last_ding
    - last_motion
    - wifi_signal_category

camera:
  - platform: ring

binary_sensor:
  - platform: ring
    scan_interval: 15
